### ISSUE TITLE
New Idea / Feature Request

### ISSUE THREAD

**Issue by SebastianRau** [googleben/ArmaCOM#2]
Hey Guys,
I really love your idea an how easy its working!
What about if you add a second data channel and adding TCP/IP Server to your tool. 
A lot of pepole love to use ESP wifi Modues and co. for tinkering.
So if multiple ESP modules are able to connect to the Arma PC via TCP IP you will shift your mod to next level :P
Also other tools on the PC could use the connection via localhost. 
Looking forward to hear from you!

Kind Regards

Sebastian 
https://kommando-wildsau.de/

**Comment by googleben** [comment]
This is actually already on my list! I'll be working on it when I have time, so if you have any input or requests, I'd love to hear them. As of right now my plan is to add a bit more structure to the extensions calls, something like handing out a UUID when a connection is made (by e.g. "connectCOM" or "connectTCP") and requiring that as an argument to further calls.

**Comment by SebastianRau** [comment]
Sounds really nice. Let me know how i can contribute :)

**Comment by FatLurch** [comment]
Mind reader: I just had two ESP32s show up in the mail, haha

**Comment by FatLurch** [comment]
I think this can be closed one the beta is finalized

**Comment by googleben** [comment]
The 2.0 beta includes TCP support which seems to be working pretty well so far. I'll consider this issue closed, and the changes should hopefully be finalized and ready to be added to the Steam Workshop package pretty soon, once I finish up a few more changes I'd like to make. In case anyone has any further issues with TCP, or questions/comments/concerns, I'd love to hear them, so don't hesitate to open a new issue.
